sudo: false
language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8
install:
  - "[ $CXX = g++ ] && export CXX=g++-8 || true"
script:
  - make

notifications:
  webhooks:
    urls:
      - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MHJvZG9scGhlJTNBbHVuYWkucmUvJTIxVVZUSk54SGhaR3d4cm1LYWZRJTNBbHVuYWkucmU"
    on_success: always  # always|never|change
    on_failure: always
    on_start: never